# NASA randomized and recommissioned battery dataset

An accelerated Life Testing Dataset for Lithium-Ion Batteries with Constant and Variable Loading Conditions:

The dataset repository is organized into three main folders, each containing one group of life cycled battery packs. 
Within each folder individual battery packs own their dedicated csv file for continuous data logging, which are named with their respective battery pack number.

The folders are named: 

- regular_alt_batteries: Containing one csv file for each battery pack cycled at the same load level or load range throughout lifetime
- recommissioned_batteries: Containing one csv file for each battery pack cycled at different load levels at varying life stages
- second_life_batteries: Containing one csv file for each second life battery pack cycled at constant current througout the second life 

The columns in each csv file contain the following data with the provided units: 

The following columns contain data throughout the cycling process: 

- start time: [mm:dd:yyyy hh:mm:ss] (start time of each cycle day for each battery pack, in most cases approximately 24h)
- relative time: [s] (the relative time is continuous from the beginning of the entire life cycle to the failure of each battery pack)
- mode: -1 = discharge, 0 = rest, 1 = charge
- voltage charger: [V] (continuous battery pack voltage measurement right after the connection of the battery pack to the charger board)
- temperature battery: [C] (continuous temperature measurement on the battery cell electrode surface)

Those columns only contain data when the respective battery is connected to the load board and performing a discharge mission

- voltage load: [V] (battery pack voltage measured on the load board)
- current load: [A] (discharge current measured on the load board using current sense resistors)
- temperature mosfet: [C] (temperature on the load board mosfets, measured for safety purposes)
- temperature resistor: [C] (temperature on the load board current sense resistor, measured for safety purposes)
- mission type: 0 = reference discharge (constant current at 2.5A), 1 = regular mission

Please cite this dataset using:

```
@misc{2023_alt_dataset_fricke_et_al,
	Author = {Kajetan Fricke and Renato G. Nascimento and Felipe A. C. Viana},
	Doi = {},
	Howpublished = {},
	Month = {July},
	Publisher = {nasa-data@lists.arc.nasa.gov},
	Title = {An accelerated Life Testing Dataset for Lithium-Ion Batteries with Constant and Variable Loading Conditions},
	Url = {},
	Version = {0.0.1},
	Year = {2023}}
```

The corresponding reference entry should look like: 
An accelerated Life Testing Dataset for Lithium-Ion Batteries with Constant and Variable Loading Conditions, v0.0.1, 

### Publications

The following publications out of the PML-UCF research group used/referred to this repository:
- K. Fricke, R. G. Nascimento, M. Corbetta, C. S. Kulkarni, F. A. C. Viana, "[Prognosis of Li-ion Batteries Under Large Load Variations Using Hybrid Physics-Informed Neural Networks]"
- K. Fricke, R. G. Nascimento, M. Corbetta, C. S. Kulkarni, F. A. C. Viana, "[An accelerated Life Testing Dataset for Lithium-Ion Batteries with Constant and Variable Loading Conditions]"


## Regular accelerated life test (regular alt batteries folder):

This folder contains the data files from battery packs subject to constant and variable loading conditions, 
where the current range of the latter remains the same throughout the battery life.

The assigned battery packs in this folder are numbered as
follows:

– Constant current:
Those battery packs were subjected to the same load level during discharge missions over their respective life time.

The here provided averaged current levels are approximated, and might vary slightly:

* 9.30A: Battery pack 0.1 and 1.1
* 12.9A: Battery pack 3.1 and 2.2
* 14.3A: Battery pack 2.3 and 5.2
* 16.0A: Battery pack 0.0 and 1.0
* 19.0A: Battery pack 2.0, 3.0 and 2.1

– Variable current:

Those battery packs are subjected to variable current within a discharge cycle.
The current level segments are kept constant for either 40, 60 or 80 seconds before switching to another level.
Both, the amplitude and length of each current level segments was randomly selected to create a pool of different random loading discharge missions.

The here provided averaged current levels are approximated, and might vary slightly:

* 14.3A average (12.9A - 16A range): Battery pack 4.1 and 5.1
* 17.0A average (16A - 19A range): Battery pack 4.0 and 5.0


## Recommissioned batteries (recommissioned batteries folder):

This folder contains the data files from battery packs where the constant loading conditions were changed throughout the battery life. 
The assigned battery packs in this folder are numbered as follows:

– Two life stages:
The following batteries were subjected to constant current levels at the first provided amplitudes until reaching an capacity level of approximately 2.2Ah,
and then switched to the second current level until reaching end of life

The here provided averaged current levels are approximated, and might vary slightly:

* 16A, 14.3A: Battery pack 3.2
* 14.3A, 16A: Battery pack 5.3
* 16A, 12.9A: Battery pack 0.2 and 3.3
* 16A, 9.30A: Battery pack 1.2 and 2.4

– Three life stages:
Those batteries were subjected to current level switches at approximately 2.2Ah and 2.0Ah of capacity.
The here provided averaged current levels are approximated, and might vary slightly:

* 16A, 14.3A, 7.5A: Battery pack 0.3
* 16A, 7.5A, 14.3A: Battery pack 2.5


## Second life batteries (second life batteries folder):

This folder contains the data files from battery packs that consist of battery cells survived from previously cycled battery packs. 
The assigned battery packs in this folder are numbered as follows:

– 2nd life battery packs:
The following batteries were subjected to constant current levels at the first provided amplitudes until reaching end of life (EOL).
Survivor cells were then reused and subjected to the second provided current level until reaching EOL

The here provided averaged current levels are approximated, and might vary slightly:

* 16.0A, 9.3A: Battery pack 1.3 (First life battery packs: 0.0 & 1.1)
* 14.3A, 7.5A: Battery pack 3.6 (First life battery packs: 2.3 & 5.2)
* 12.9A, 5.0A: Battery pack 5.4 (First life battery packs: 2.2 & 3.1)

## Download URL: https://data.nasa.gov/docs/legacy/battery_alt_dataset.zip

## Einlesen der Daten
Für ersten Überblick der Daten battery20.csv ideal (nur ca. 30 Zyklen)

In [1]:
import pandas as pd
import numpy as np

battery_label = "battery20"
file = battery_label + ".csv"
base_path = "battery_alt_dataset/battery_alt_dataset/regular_alt_batteries/"
full_path = base_path + file

df_in = pd.read_csv(full_path)
df_in.tail(3)

,start_time,time,mode,voltage_charger,temperature_battery,voltage_load,current_load,temperature_mosfet,temperature_resistor,mission_type
207388,2022-07-24 22:39:00,203449.607,0.0,7.07,22.152,NaN,NaN,NaN,NaN,NaN
207389,2022-07-24 22:39:00,203450.551,0.0,7.07,22.152,NaN,NaN,NaN,NaN,NaN
207390,2022-07-24 22:39:00,203451.494,0.0,7.07,22.155,NaN,NaN,NaN,NaN,NaN

In [2]:
df_in.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207391 entries, 0 to 207390
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   start_time            207391 non-null  object
 1   time                  207391 non-null  float64
 2   mode                  207391 non-null  float64
 3   voltage_charger       207391 non-null  float64
 4   temperature_battery   207391 non-null  float64
 5   voltage_load          18927 non-null   float64
 6   current_load          18927 non-null   float64
 7   temperature_mosfet    18927 non-null   float64
 8   temperature_resistor  18927 non-null   float64
 9   mission_type          18927 non-null   float64
dtypes: float64(9), object(1)
memory usage: 15.8+ MB

In [3]:
df_in.describe(include='all')

,start_time,time,mode,voltage_charger,temperature_battery,voltage_load,current_load,temperature_mosfet,temperature_resistor,mission_type
count,207391,207391.000000,207391.000000,207391.000000,207391.000000,18927.000000,18927.000000,18927.00000,18927.000000,18927.000000
unique,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2022-07-23 12:31:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,103222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,101473.306765,0.383667,7.381259,34.613413,6.653623,13.079694,28.83167,29.925495,0.624663
std,NaN,58928.063113,0.647297,0.909755,17.688532,0.734256,8.253379,3.38615,5.664600,0.484223
min,NaN,0.000000,-1.000000,-0.115000,0.000000,-0.026000,0.150000,19.57000,22.590000,0.000000
25%,NaN,50294.057500,0.000000,6.744000,22.790000,6.191000,2.521000,24.87000,22.960000,0.000000
50%,NaN,101674.111000,0.000000,7.475000,28.784000,6.612000,19.424410,30.36000,33.130000,1.000000
75%,NaN,152081.177000,1.000000,8.252000,34.594000,7.030500,19.584991,31.86000,35.170000,1.000000
max,NaN,203451.494000,1.000000,9.161000,109.165000,8.707000,19.781938,33.61000,36.090000,1.000000

## Reinigen der Daten
* Nicht benötigte Spalten entfernen: start_time, voltage_load, temperature_mosfet, temperature_resistor
* Fehlende Werte ersetzen: mission_type, teilweise temperature_battery
* Unsinnige Werte ersetzen: Temperaturen werden nach unten auf 15 °C begrenzt (selten Ausreißer bis auf -100 °C)
* Unsinnige Werte entfernen: Teilweise 0V im Ladevorgang
* Spalten umbenennen: 'voltage_charger'->'voltage', 'temperature_battery'->'temperature'
* delta_t berechnen

In [4]:
#Clean data and drop not used columns
def clean_data(df_in):
    df = df_in.copy()
    df['temperature_battery'] = df['temperature_battery'].astype(float)

    # fill NA values of mission_type with 1 (normal mission)
    df['mission_type'] = df['mission_type'].fillna(1.0)
    
    # fill NA values of temperature and replace unrealistic values
    mean_temp = df['temperature_battery'].mean()
    df['temperature_battery'] = df['temperature_battery'].fillna(mean_temp)
        
    df['temperature_battery'] = df['temperature_battery'].apply(lambda x: max(x,15))
    df['current_load'] = df['current_load'].fillna(0)
    df = df.drop(columns=['start_time','temperature_mosfet','temperature_resistor','voltage_load'])

    #Rename voltage_charger to voltage, since there is only one voltage left, same with temperature
    df.rename(columns={'voltage_charger':'voltage'}, inplace=True)
    df.rename(columns={'temperature_battery':'temperature'}, inplace=True)
    
    # remove voltage zero values
    df = df[df['voltage'] != 0].copy()
    
    # reset index
    df.reset_index(drop=True, inplace=True)
    
    # delta t berechnen
    df['delta_t'] = df['time'].diff().fillna(0)
    
    return df

In [5]:
df = clean_data(df_in)
df.to_csv("cleaned_data_"+file)
df.tail(3)

,time,mode,voltage,temperature,current_load,mission_type,delta_t
207386,203449.607,0.0,7.07,22.152,0.0,1.0,0.943
207387,203450.551,0.0,7.07,22.152,0.0,1.0,0.944
207388,203451.494,0.0,7.07,22.155,0.0,1.0,0.943

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207389 entries, 0 to 207388
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   time          207389 non-null  float64
 1   mode          207389 non-null  float64
 2   voltage       207389 non-null  float64
 3   temperature   207389 non-null  float64
 4   current_load  207389 non-null  float64
 5   mission_type  207389 non-null  float64
 6   delta_t       207389 non-null  float64
dtypes: float64(7)
memory usage: 11.1 MB

## Feature Engineering
* Generiert aus zeitbasierten Features zyklusbasierte Features
* Kumulierte Features:
    * time_sec: Betriebsdauer in Sekunden
    * EFC: Äquivalente Vollzyklen
    * E_cum_Wh: Entladene Energie in Wh
    * T_cum_avg: Durchschnittliche kumulierte Temperatur in °C
    * T_cum_max: Maximale kumulierte Temperatur in °C
    * T_cum_min: Minimale kumulierte Temperatur in °C
    * Temperatur Histogramm in Sekunden: 'sec_T_st_-20','sec_T_-20_0', 'sec_T_0_15', 'sec_T_15_30', 'sec_T_30_45', 'sec_T_45_60','sec_T_60_80', 'sec_T_gt_80'
    * C_rate_cum_avg: Durchschnittliche kumulierte C (Entlade-)rate
    * C_rate_cum_max: Maximale kumulierte C (Entlade-)rate
    * C rate Histogramm in Sekunden: 'sec_C_rate_0_0.5', 'sec_C_rate_0.5_1', 'sec_C_rate_1_2', 'sec_C_rate_2_3', 'sec_C_rate_3_4','sec_C_rate_4_6', 'sec_C_rate_6_8', 'sec_C_rate_gt_8'
    * sec_at_high_voltage: Sekunden über 2*4,0V
    * sec_at_low_voltage: Sekunden unter 2*3,1V
    * integral_high_volt_high_temp: sum(max(voltage-2*4.0V, 0)*max(temperature-40°C, 0)*delta_t)
    * integral_low_volt_high_temp: sum(max(2*3,1V-voltage, 0)*max(temperature-40°C, 0)*delta_t)
    * integral_low_volt_high_discharge: sum(max(2*3,1V-voltage, 0)*max(current_load-1C, 0)*delta_t)
    * integral_high_temp_high_discharge: sum(max(temperature-40°C, 0)*max(current_load-1C, 0)*delta_t)
    * integral_low_temp_high_discharge: sum(max(0°C-temperature, 0)*max(current_load-1C, 0)*delta_t)
    * integral_discharged_squared: sum(current_load ** 2 * delta_t)
    * integral_discharged_squared_T: sum(current_load ** 2 * Tabs * delta_t)
    * sec_T_over_X: Sekunden bei der die Temperatur über X °C liegt
* Zyklusspezifische Features:
    * batt_label: Label der getesteten Batterie
    * isRefCycle: True: Referenzzyklus mit 2.5A Entladestrom, False: Normaler Zyklus
    * Q_norm_at_3.xV: Ladung die benötigt wird, um Batterie von voller Ladung auf 2*3.xV zu entladen normiert auf nominale    Kapazität.Wird nur in den Referenzzyklen berechnet, dazwischen wird linear interpoliert.
    * T_cycle_avg: Durchschnittliche Temperatur des Zyklus in °C
    * T_cycle_max: Maximale Temperatur des Zyklus in °C
    * T_cycle_min: Minimale Temperatur des Zyklus in °C
    * C_rate_cycle_avg: Durchschnittliche C (Entlade-)rate des Zyklus
    * C_rate_cycle_max: Maximale C (Entlade-)rate des Zyklus
    * R_mOhm: Gemessener (DC) Innenwiderstand in mOhm
    * SOH: State of Health (C_zyklus/C_nom) in %. Wird nur in den Referenzzyklen berechnet, dazwischen wird linear interpoliert
    * RUL_EFC: Verbleibende nutzbare Lebensdauer (Remaining useful life) in äquivalenten Vollzyklen

#### Hilfsfunktionen

In [7]:
def calc_Q_V(voltage, current, delta_t, voltage_points, nom_cap_mAh, min_start_voltage):
    '''
    Calculates the normalized discharge from full charge for given voltage points
    '''
    Q_norm = []
    if voltage[0] < min_start_voltage:
        return False, []
    i=0
    for idx in range(len(voltage_points)):
        voltage_point = voltage_points[idx]
        while i < len(voltage)-1 and voltage[i] > voltage_point:        
            i += 1
        q = (current[:i] * delta_t[:i]).sum()
        Q_norm.append(q/3.6/nom_cap_mAh)
    return True, Q_norm

def return_inner_res_mOhm(mode, current, voltage, min_current,min_volt_drop):
    '''
    Calculates the inner resistance when the mode changes from discharge to idle
    '''
    res = 0
    max_delay_sec = 10
    falseRet = (False,0)
    curr_val = 0

    discharge_idx = np.where(current > min_current)[0]

    start_idx=discharge_idx[-1]

    curr_val = current[start_idx] 
    if curr_val < min_current:
        return falseRet
    
    for offset in range(max_delay_sec):
        voltage1 = voltage[start_idx+offset]
        voltage2 = voltage[start_idx+offset+1]
        voltage_drop = voltage2 - voltage1
        if voltage_drop > min_volt_drop:
            res = 1000*voltage_drop/curr_val
            break

        if offset == max_delay_sec-1:
            return falseRet

    return True,res
    

def isReferenceCycle(mission, current):
    '''
    checks if given cycle is a reference cycle with 2.5A discharge
    '''
    for i in range(len(current)):
        if (mission[i] == 0) and (2 < current[i] < 3):
            return True
    return False

def calc_charge(current, delta_t):
    '''
    calculates the full charge throuput for the given data
    '''
    charge_As = (current*delta_t).sum()
    charge_mAh = charge_As / 3.6
    return charge_mAh

def calc_energy(current, voltage, delta_t):
    '''
    calculates the full energy throuput for the given data
    '''
    energy_Ws = (current * voltage * delta_t).sum()
    energy_Wh = energy_Ws / 3600
    return energy_Wh

def calc_hist(feature, delta_t, bins):
    '''
    Calculates histogram and avg,max,min for a given feature
    '''
    hist = [0]*(len(bins)+1)

    maxi = feature.max()
    avg = (feature * delta_t).sum() / delta_t.sum()
    mini = feature.min()

    bins = [-np.inf] + bins + [np.inf]
    
    for i in range(0,len(bins)-1):
        bool_idx = (feature >= bins[i]) & (feature < bins[i+1])
        hist[i] = delta_t[bool_idx].sum()
    
    return hist, maxi, avg, mini

def calc_thres_times(feature, delta_t, thres):
    '''
    Calculate time over thresholds
    '''
    thres_times = [0]*(len(thres))
    for i in range(len(thres)):
        thres_times[i] = delta_t[feature >= thres[i]].sum()

    return thres_times

def integrate_two_feature_product(delta_t, feature1, operand1, thres1, feature2, operand2, thres2):
    '''
    integrates product of two features over time with given threshold, with operand 'gt' for
    'greater than' or operand 'lt' for 'lower than'
    '''
    features = [feature1, feature2]
    operands = [operand1, operand2]
    thresholds = [thres1, thres2]
    diffs = 2*[0]
    i=0
    for feature, operand, thres in zip(features, operands, thresholds):
        if operand == 'gt':
            diffs[i] = np.maximum(feature-thres, 0)
        elif operand == 'lt':
            diffs[i] = np.maximum(thres-feature, 0)
        else: #invalid operand
            return 0
        i += 1
    integral = (diffs[0] * diffs[1] * delta_t).sum()
    return integral

        
def return_full_charged_cycle_indices(mode, voltage, charged_volt, discharged_volt):
    '''
    return all indices where a new cycle starts
    '''
    indices = []
    max_idx = len(mode) - 1
    i=0
    idx_step = 10
    
    # check time when battery is fully charged
    while i < max_idx:
        if mode[i] == 0 and voltage[i] >= charged_volt:
            break
        i += idx_step
    
    while i < max_idx:
        indices.append(i)
        # wait until battery is discharging
        while (i < max_idx) and (mode[i] != -1):
            i += idx_step
        
        # check time when battery is fully discharged
        while i < max_idx:
            if mode[i] == 0 and voltage[i] <= discharged_volt:
                break         
            i += idx_step

        # check time when battery is fully charged
        while i < max_idx:
            if mode[i] == 0 and voltage[i] >= charged_volt:
                break
            i += idx_step
            
    return indices

#### Generierung der zyklusbasierten Daten

In [19]:
def init_list_dict(d, features):
    for feature in features:
        d[feature] = []

def init_dict(d, features, val):
    for feature in features:
        d[feature] = val

features = ['test1', 'test2']
d = {}
init_dict(d, features, 0)
d['test1'] = 1
d

{'test1': 1, 'test2': 0}

In [8]:
def generate_cycle_based_data(batt_label, data):
    """
    Generate cycle based data from the time based full cycle battery test data
    """   
    d = {}

    d['batt_label'] = []
    d['isRefCycle'] = []
    d['time_sec'] = []
    d['EFC'] = []
    d['E_cum_Wh'] = []

    # Variables for Q(V) calculation
    Q_V_norm_features = ['Q_norm_at_3.9_V', 'Q_norm_at_3.8_V', 'Q_norm_at_3.7_V', 'Q_norm_at_3.6_V']
    for feature in Q_V_norm_features:
        d[feature] = []
    voltage_points = [7.8, 7.6, 7.4, 7.2]
    Q_values = [0] * len(voltage_points)

    # Variables for temperature histogram and avg,min,max calculation
    d['T_cum_avg'] = []
    d['T_cum_max'] = []
    d['T_cum_min'] = []
    d['T_cycle_avg'] = []
    d['T_cycle_max'] = []
    d['T_cycle_min'] = []
    d['sec_T_over_40'] = []
    d['sec_T_over_45'] = []
    d['sec_T_over_50'] = []
    T_hist_features = ['sec_T_st_-20','sec_T_-20_0', 'sec_T_0_15', 'sec_T_15_30', 'sec_T_30_45', 'sec_T_45_60','sec_T_60_80', 'sec_T_gt_80']
    for feature in T_hist_features:
        d[feature] = []
    temp_thres = [40,45,50]
    sum_time_temp_thres = np.array(len(temp_thres)*[0.0])
    temp_bins = [-20, 0, 15, 30, 45, 60, 80]
    temp_hist_len = len(temp_bins)+1
    temp_hist = np.array(temp_hist_len*[0.0])
    sum_temp = 0
    avg_temp = 0
    max_temp = -1000
    min_temp = 1000
    sum_time = 0

    # Variables for current histogram and avg,max calculation
    sum_discharge_time = 0
    d['C_rate_cum_avg'] = []
    d['C_rate_cum_max'] = []
    d['C_rate_cycle_avg'] = []
    d['C_rate_cycle_max'] = []
    C_hist_features = ['sec_C_rate_0_0.5', 'sec_C_rate_0.5_1', 'sec_C_rate_1_2', 'sec_C_rate_2_3', 'sec_C_rate_3_4','sec_C_rate_4_6', 'sec_C_rate_6_8', 'sec_C_rate_gt_8']
    for feature in C_hist_features:
        d[feature] = []
    curr_bins_C = [0.5,1,2,3,4,6,8]
    curr_hist_len = len(curr_bins_C)+1
    curr_hist = np.array(curr_hist_len*[0.0])
    sum_curr_C = 0
    avg_curr = 0
    max_curr_C = -1000

    # Variables for ov/uv calculations
    high_volt_thres = 8.0
    low_volt_thres = 6.2
    curr_C_thres = 1.0
    volt_hist_len = 3
    volt_hist = np.array(volt_hist_len*[0.0])
    integral_high_volt_high_temp = 0
    integral_low_volt_high_temp = 0
    integral_low_volt_high_discharge = 0
    d['sec_at_high_voltage'] = []
    d['sec_at_low_voltage'] = []
    d['integral_high_volt_high_temp'] = []
    d['integral_low_volt_high_temp'] = []
    d['integral_low_volt_high_discharge'] = []

    # Variables for high discharge and high or low temperatures
    low_temp_thres = 0
    high_temp_thres = 40.0
    integral_high_temp_high_discharge = 0
    integral_low_temp_high_discharge = 0
    d['integral_high_temp_high_discharge'] = []
    d['integral_low_temp_high_discharge'] = []

    # Variables for sum(Crate^2*dt)
    integral_discharge_squared = 0
    integral_discharge_squared_T = 0
    d['integral_discharge_squared'] = []
    d['integral_discharge_squared_T'] = []


    d['R_mOhm'] = []
    d['SOH'] = []
    d['RUL_EFC'] = []

    sum_Q_mAh = 0
    sum_E_Wh = 0

    res_mOhm = 50
    nom_capacity_mAh = 2450

    ref_indices = []

    mode_complete = data['mode'].to_numpy()
    mission_complete = data['mission_type'].to_numpy()
    time_complete = data['time'].to_numpy()
    delta_t_complete = data['delta_t'].to_numpy()
    current_complete = data['current_load'].to_numpy()
    temp_complete = data['temperature'].to_numpy()
    voltage_complete = data['voltage'].to_numpy()

    # Get indices for every full cycle at full charge
    indices = return_full_charged_cycle_indices(mode_complete, voltage_complete, 8, 6.5)
 
    for i in range(0,len(indices)-1):
        d['batt_label'].append(batt_label)
        start_idx = indices[i]
        end_idx = indices[i+1]

        mode = mode_complete[start_idx:end_idx]
        mission = mission_complete[start_idx:end_idx]
        time = time_complete[start_idx:end_idx]
        delta_t = delta_t_complete[start_idx:end_idx]
        current_A = current_complete[start_idx:end_idx]
        current_C = 1000 * current_A / nom_capacity_mAh
        temp = temp_complete[start_idx:end_idx]
        voltage = voltage_complete[start_idx:end_idx]
        
        referenceCycle = isReferenceCycle(mission, current_A)
        d['isRefCycle'].append(referenceCycle)
        d['time_sec'].append(time[-1])

        charge_mAh = calc_charge(current_A, delta_t)
        energy_Wh = calc_energy(current_A, voltage, delta_t)

        sum_Q_mAh += charge_mAh
        sum_E_Wh += energy_Wh

        if referenceCycle:
            ref_indices.append(i)
            ret, Q_values = calc_Q_V(voltage, current_A, delta_t, voltage_points, nom_capacity_mAh, 8)
            soh = 100 * charge_mAh / nom_capacity_mAh
            if not ret:
                Q_values = [0] * len(voltage_points)
                soh = 0
        else:
            Q_values = [0] * len(voltage_points)
            soh = 0

        for i, feature in enumerate(Q_V_norm_features):
            d[feature].append(Q_values[i])

        d['SOH'].append(soh)
        
        sum_Q_norm = sum_Q_mAh / nom_capacity_mAh

        d['EFC'].append(sum_Q_norm)
        d['E_cum_Wh'].append(sum_E_Wh)

        #Calculate inner resistance
        meas_ok, tmp_res = return_inner_res_mOhm(mode, current_A, voltage, 2.0,0.1)
        if meas_ok:
            res_mOhm = tmp_res 
        d['R_mOhm'].append(res_mOhm)

        # Do calculations for UV/OV
        # Do calculations for time at high/low voltage
        voltage_hist_cycle, dummy1, dummy2, dummy3 = calc_hist(voltage,delta_t,[low_volt_thres, high_volt_thres])
        volt_hist += np.array(voltage_hist_cycle)
        d['sec_at_high_voltage'].append(volt_hist[-1])
        d['sec_at_low_voltage'].append(volt_hist[0])

        # Do calculation for high voltage high temperature integral
        integral_high_volt_high_temp += integrate_two_feature_product(delta_t, temp, 'gt',\
                                        high_temp_thres, voltage, 'gt', high_volt_thres)
        d['integral_high_volt_high_temp'].append(integral_high_volt_high_temp)

        # Do calculation for low voltage high temperature integral
        integral_low_volt_high_temp += integrate_two_feature_product(delta_t, temp, 'gt',\
                                        high_temp_thres, voltage, 'lt', low_volt_thres)
        d['integral_low_volt_high_temp'].append(integral_low_volt_high_temp)

        # Do calculation for low voltage high discharge current integral
        integral_low_volt_high_discharge += integrate_two_feature_product(delta_t, current_C, 'gt',\
                                                curr_C_thres, voltage, 'lt', low_volt_thres)
        d['integral_low_volt_high_discharge'].append(integral_low_volt_high_discharge)


        # Do calculation for high discharge and high/low temperatures
        # Do calculation for high temp and high discharge current intagral
        integral_high_temp_high_discharge += integrate_two_feature_product(delta_t, temp, 'gt',\
                                            high_temp_thres, current_C, 'gt', curr_C_thres)
        d['integral_high_temp_high_discharge'].append(integral_high_temp_high_discharge)

        
        #integral_low_temp_high_discharge = 0
        integral_low_temp_high_discharge += integrate_two_feature_product(delta_t, temp, 'lt',\
                                            low_temp_thres, current_C, 'gt', curr_C_thres)
        d['integral_low_temp_high_discharge'].append(integral_low_temp_high_discharge)

        
        #Do temperature calculations here
        temp_hist_cycle, max_temp_cycle, avg_temp_cycle, min_temp_cycle = calc_hist(temp,delta_t,temp_bins)
        temp_hist += np.array(temp_hist_cycle)
        sum_temp += (temp * delta_t).sum()
        sum_time += delta_t.sum()
        avg_temp = sum_temp / sum_time
        if max_temp_cycle > max_temp:
            max_temp = max_temp_cycle
        if min_temp_cycle < min_temp:
            min_temp = min_temp_cycle

        temp_times = calc_thres_times(temp, delta_t, temp_thres)
        sum_time_temp_thres += np.array(temp_times)

        d['sec_T_over_40'].append(sum_time_temp_thres[0])
        d['sec_T_over_45'].append(sum_time_temp_thres[1])
        d['sec_T_over_50'].append(sum_time_temp_thres[2])

        d['T_cycle_avg'].append(avg_temp_cycle)
        d['T_cycle_max'].append(max_temp_cycle)
        d['T_cycle_min'].append(min_temp_cycle)
        d['T_cum_avg'].append(avg_temp)
        d['T_cum_max'].append(max_temp)
        d['T_cum_min'].append(min_temp)
        for i, feature in enumerate(T_hist_features):
            d[feature].append(temp_hist[i])
        
        #Do current calculations here  
        curr_hist_cycle, max_curr_cycle_A, dummy, min_curr_cycle_A = calc_hist(current_C, delta_t, curr_bins_C)
        curr_hist += np.array(curr_hist_cycle)
        
        cycle_sum_curr_C = (current_C * delta_t).sum()
        sum_curr_C += cycle_sum_curr_C
        cycle_discharge_time = delta_t[mode == -1].sum()
        sum_discharge_time += cycle_discharge_time
        avg_curr_cycle_C = cycle_sum_curr_C / cycle_discharge_time
        avg_curr_C = sum_curr_C / sum_discharge_time
        max_curr_cycle_C = current_C.max()
        if max_curr_cycle_C > max_curr_C:
            max_curr_C = max_curr_cycle_C

        d['C_rate_cycle_avg'].append(avg_curr_cycle_C)
        d['C_rate_cycle_max'].append(max_curr_cycle_C)
        d['C_rate_cum_avg'].append(avg_curr_C)
        d['C_rate_cum_max'].append(max_curr_C)
        for i, feature in enumerate(C_hist_features):
            d[feature].append(curr_hist[i])

        # Do calculations for one dimensional quadratic integral for current
        C_squared = current_C ** 2
        integral_discharge_squared += (C_squared * delta_t).sum()
        d['integral_discharge_squared'].append(integral_discharge_squared)

        integral_discharge_squared_T += (C_squared * abs(temp-20.0) * delta_t).sum()
        d['integral_discharge_squared_T'].append(integral_discharge_squared_T)

        
  
    # Make linear interpolation for Q(V)
    max_idx = max(ref_indices)
    min_idx = min(ref_indices)

    lin_int_features = ['SOH'] + Q_V_norm_features
       
    for i in range(0,len(indices)-1):
        if i > max_idx:
            for feature in lin_int_features:
                d[feature][i] = d[feature][max_idx]
        elif i < min_idx:
            for feature in lin_int_features:
                d[feature][i] = d[feature][min_idx]
        elif i not in ref_indices:
            for j,v in enumerate(ref_indices):
                if v > i:
                    # Found right index
                    x = 2*[0]
                    y = 2*[0]
                    x[0] = d['EFC'][ref_indices[j-1]]
                    x[1] = d['EFC'][v]
                    for feature in lin_int_features:
                        y[0] = d[feature][ref_indices[j-1]]
                        y[1] = d[feature][v]
                        x_interp = d['EFC'][i]
                        y_interp = np.interp(x_interp, x, y)     
                        d[feature][i] = y_interp
                    break

    # Calculate RUL in EFC
    for efc in d['EFC']:
        d['RUL_EFC'].append(d['EFC'][-1]-efc)

        
    ret = pd.DataFrame(d)
    return ret

## Erstellung Datensatz
* Alle Funktionen kombiniert
* Erstellung eines Datensatzes mit mehreren Batterielabels
* Kann für ML oder explorative Datenanalyse benutzt werden

In [9]:
def create_cycle_data_frame(labels, base_path):
    complete_df = pd.DataFrame([])
    for label in labels:
        print(label)
        csv_name = label + ".csv"
        full_path = base_path + csv_name
        df_in = pd.read_csv(full_path)
        df_cleaned = clean_data(df_in)
        cycle_df = generate_cycle_based_data(label,df_cleaned)
        complete_df = pd.concat([complete_df,cycle_df],axis=0)
    return complete_df

In [10]:
batt_labels = ['battery02','battery03','battery12','battery24','battery25','battery32','battery33','battery53']
base_path = "battery_alt_dataset/battery_alt_dataset/recommissioned_batteries/"

complete_recommissioned_df = create_cycle_data_frame(batt_labels,base_path)
complete_recommissioned_df.to_csv("recommissioned_complete.csv", index=False)

battery02
battery03

C:\Users\User\AppData\Local\Temp\ipykernel_8144\4079203112.py:7: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_in = pd.read_csv(full_path)

battery12
battery24
battery25
battery32
battery33
battery53

In [11]:
batt_labels = ['battery00','battery01','battery10','battery11','battery20','battery21','battery22',\
              'battery23','battery30','battery31','battery40','battery41','battery50','battery51','battery52']
base_path = "battery_alt_dataset/battery_alt_dataset/regular_alt_batteries/"

complete_reg_alt_df = create_cycle_data_frame(batt_labels,base_path)
complete_reg_alt_df.to_csv("reg_alt_complete.csv", index=False)

battery00
battery01
battery10
battery11
battery20
battery21
battery22

C:\Users\User\AppData\Local\Temp\ipykernel_8144\4079203112.py:7: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_in = pd.read_csv(full_path)

battery23
battery30

C:\Users\User\AppData\Local\Temp\ipykernel_8144\4079203112.py:7: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_in = pd.read_csv(full_path)

battery31
battery40
battery41
battery50
battery51
battery52

In [12]:
complete_df = pd.concat([complete_reg_alt_df,complete_recommissioned_df],axis=0)
complete_df.to_csv("data_complete.csv", index=False)
print("Done!")

Done!